### ISSUE TITLE
Hi Richard

### ISSUE THREAD

**Issue by neozhaoliang** [richardassar/zpipe-native#1]
Hi Richard: could you upload your code for [the video on youtube](https://www.youtube.com/watch?v=Vi_6x-VpAb0&lc=z13sytsh3nrswdgp504cjxgynprecntr0s40k.1488727369610473)? A coarse version would also be very helpful. Thanks !

**Comment by richardassar** [comment]
Hi, sure. Please give me a little time as I have to search through a lot of stuff to find it. In the process I will find some other projects which I'm sure you will find interesting.

I'll update you and put a message here when it's online.

Thanks :)

**Comment by neozhaoliang** [comment]
great! hoping for your stuff !

2017-03-07 7:54 GMT+08:00 The_Fly <notifications@github.com>:

**Comment by neozhaoliang** [comment]
Hi Richard: How is your work going on? I think I can't wait to learn new things from you ...
